kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: operator-utils-api-service
spec:
  lookupPolicy:
    local: false
---

kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: operator-utils-api-service
spec:
  source:
    git:
      uri: https://github.com/monkey1016/ocp4-operator-catalog-management-utils.git
      ref: khaled-build
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: operator-utils-api-service:latest